---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets.yaml
  - synapse-signing-key-secrets.yaml
  - synapse-configmap.yaml
  - synapse-log-configmap.yaml
  - livekit-configmap.yaml
  - coturn-configmap.yaml
  - synapse.yaml
  - livekit.yaml
  - lk-jwt.yaml
  - synapse-admin.yaml
  - coturn.yaml
  - ingress.yaml
