apiVersion: v1
kind: Secret
metadata:
    name: matrix-secrets
    namespace: matrix
type: Opaque
stringData:
    SYNAPSE_SHARED_SECRET: ENC[AES256_GCM,data:9jRABIp/KYvD/Q==,iv:A1yqnMZ62hZGoFMTmfHUvSisRxfo0x4lQ8emYcKyQgI=,tag:BKMIgzCHM6I4/Nn1uHYkXw==,type:str]
    REGISTRATION_SHARED_SECRET: ENC[AES256_GCM,data:2sx/94hcKzS0MQ==,iv:RWIAnr87wmTrbpeCupCamx9FBkUXxJyk/cP7dufxgzw=,tag:fhONnFjC3VK2iEa04GQRvQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:DeEDtCxem0FYNA==,iv:nQG9nEpQem+tr7wKOXozPN4llyZTZhXug16dgi+GDMw=,tag:rzVmcJHkHHZUDdKgw2Hb9A==,type:str]
    LIVEKIT_API_KEY: ENC[AES256_GCM,data:RTO+zIMSIvnjpQ==,iv:YwK9sD2PGBola1eWcJJE3hi6ZGbtj/pgADzIvfVGheg=,tag:CdYfDiB+Ju+0/0Gow285Bw==,type:str]
    LIVEKIT_API_SECRET: ENC[AES256_GCM,data:QR7SFHqa+WKnAA==,iv:Ic9KW20w+jY1bNi4U1NSXp9XcsC+hvb4pHulUocxJNI=,tag:/Kpuq+94CPKPT0WVF0CM1w==,type:str]
    COTURN_AUTH_SECRET: ENC[AES256_GCM,data:pS+1ku6Ok49ZiQ==,iv:rojWsNa3zm133ojwz2LYKam9WjKBXNYJmEHd8feAr/w=,tag:s93fxUQcXBhxkQe1MNkVdg==,type:str]
    FORM_SECRET: ENC[AES256_GCM,data:8Kfb9agg8x56PQ==,iv:6UWxzoOapW398K3rCRQTRFb7hIPIsrtnH1IrGL/3Wpk=,tag:hqmbQfL1lwOwT9WlSyfYfA==,type:str]
sops:
    age:
        - recipient: age1qt6zwvjzpvz8sed88tf3wj96t7694nnprnqdjls0w9vkxzzm6d8qag8snq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTjVvZGRZakJJSFVFdG5T
            bStWakFqci80blMvUU0ra1d1a3cvMUphQ21BCkJnZFFYT1dVNHAwR1dEUy9OeWxo
            UGJBOE8vakhnaDRRSjlnOEZXdTBqVncKLS0tIFRqbTYzZ0VKRjlPQ25KTUx4RWhR
            cmhqaGI2Q1MrQVBReXN3UGwxOUhkS0EKumoNivpCQn4vUbPFusjO/aL1YSKc8OSI
            Gj0WxDI4wW5+uClhBv2pjyWaI0VRoroQlznRMQ0Ddt6ibpelUxG9Tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T04:53:57Z"
    mac: ENC[AES256_GCM,data:AnOHtNAB+7Ylj10o5VVGzSDy689ZYzxcrHrCTGNIeTmyv+HgBe2MgD8/6Zk0aryQjOggztapYgDGr+Nq9DrHOIPx/+gXTO0SuaQwZ9FAp+57vkoHufh0hoeLcxpKSwAb5cQUijOBCJyFlZuX3lS4WrkRiHcnS7NSk2js1F5Wtbc=,iv:3yu3O5Ukgp3ReW6OjTyqpQuzmJbkssLuAkHxCsbDOWs=,tag:acENdx6u9YwwzvCEvPVkpw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
