apiVersion: v1
kind: Secret
metadata:
    name: matrix-secrets
    namespace: matrix
type: Opaque
stringData:
    SYNAPSE_SHARED_SECRET: ENC[AES256_GCM,data:pfS/+ri2fJqIM4iw1n3RmYWB63QxiA4qrEMV9hq3IxUg/2JRpeV9TrAT4B/JmSv6GKcy1MT7ZqMdTlSEmvPVVA==,iv:PR9xvsrQQzxGmk0mj1Smm9M9d6IF/675oKtFXyVdnXA=,tag:pq2DAxirtNqnDegapJsSgg==,type:str]
    REGISTRATION_SHARED_SECRET: ENC[AES256_GCM,data:JnmN0G2VCHdJHsUeV20VlR79D3RguqbrZTaSHxgA2V4g4JhmvkXai+2Z2DSQ5WEOudfsCBUhn1no9+ec0sX6dQ==,iv:Zel3bXuI/v2YUhk5detraZR9Dxl2hMUcCbadr+w8m7I=,tag:PSHfPrx7roDdlq7O3hykTw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:zvg2Ny6pbCQOIhlToK6AqLWJvEQUONnP0dZZ5BPsWMujAgLbxnBz5uKzYIzHklSKS3s2bUcsFofq2Fd2uTZ1MA==,iv:/fx83l1AIQGuXz2fGaK2iNAKmqsTe8nzKQ3sxA5WKHg=,tag:FQ8o9GRxnrpbZplmRZxSDA==,type:str]
    LIVEKIT_API_KEY: ENC[AES256_GCM,data:Qi+7udGzO5CCUdGUXidARRrBBxTCvuRUYLmNHwY8EBqE5pcxMagbnSSWtbrjOOjPFV45k48RPnRDlCbshjnD+A==,iv:0zlxbSubzxVrNTwtnqmRRL21Tk4SzR3YoIO9rWPwcsI=,tag:pvp9jaIxnQuFGtRPRArYPA==,type:str]
    LIVEKIT_API_SECRET: ENC[AES256_GCM,data:czy/OrgUVjpwEzTKFvpdA4Dh4r3g0TotaJNtCHf5CxSZSvGBl1/+i/1Afv63DS5R/d0MWqvfMIpZFZu9Ul2gaw==,iv:7vwbiAkuu021CzXx4a5GJ7vC0cu4RiVOzO2fAiargxQ=,tag:ff5QPFv2cDsO6Uk2PYQEog==,type:str]
    COTURN_AUTH_SECRET: ENC[AES256_GCM,data:XZ9gZY/Mc9Lda8TJ1mzIbUdeuHfi8zoNFq4kLoeHvt4f1zqc3we7zM/EJgNNB983neBJ48UXbAnjJwPAlV7vAw==,iv:shC9Smq6cava1c5PT1VLN3Qc+YL8WvimWtyLTFHn11Y=,tag:1MBfy3oGpRUj3lKiHgkAzQ==,type:str]
    FORM_SECRET: ENC[AES256_GCM,data:jr2EQQ4o9nXd1saAsMOtth84x7P2W62Pj9rRhLF2U2viB1b78ODJvFxwr4tx9DsBdTYDzFzRHNrwjxzZEFPFHw==,iv:/JBFhJ3Bn5ruGeWDUFDSq5yqO5LayOSiaJADMQNOx/A=,tag:mvEdO7o4y5wFq2NiuDMq4w==,type:str]
sops:
    age:
        - recipient: age1qt6zwvjzpvz8sed88tf3wj96t7694nnprnqdjls0w9vkxzzm6d8qag8snq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTjVvZGRZakJJSFVFdG5T
            bStWakFqci80blMvUU0ra1d1a3cvMUphQ21BCkJnZFFYT1dVNHAwR1dEUy9OeWxo
            UGJBOE8vakhnaDRRSjlnOEZXdTBqVncKLS0tIFRqbTYzZ0VKRjlPQ25KTUx4RWhR
            cmhqaGI2Q1MrQVBReXN3UGwxOUhkS0EKumoNivpCQn4vUbPFusjO/aL1YSKc8OSI
            Gj0WxDI4wW5+uClhBv2pjyWaI0VRoroQlznRMQ0Ddt6ibpelUxG9Tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T20:16:41Z"
    mac: ENC[AES256_GCM,data:rQOYvDt1QIvBYgqpVqlRHL18I+VEwdrqRJHeWucEy/TVk+W1V858adlcdBsiJqENjlFSklI/bulDp1comtNgtBoEpp3mRiX2P4T15G1HLTiVZZNjtwWnf0EK3u51AbGInndpO3zG5AjzNuHciJWThWT2ZAeVb5+GgoBLDY2MRIQ=,iv:TKZGtdQXgGh07saR5xksQNGtT5fIA9leX5Q8JN+3ems=,tag:7DAHe4UYKQhUHlDmBLy0Wg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
