---
apiVersion: v1
kind: ConfigMap
metadata:
  name: synapse-log-config
  namespace: matrix
  labels:
    app.kubernetes.io/part-of: jellybuntu
data:
  synapse-log.config: |
    version: 1

    formatters:
      precise:
        format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s'

    handlers:
      console:
        class: logging.StreamHandler
        formatter: precise
        stream: ext://sys.stdout

    loggers:
      synapse.storage.SQL:
        level: WARNING
      synapse.access.http.8008:
        level: WARNING

    root:
      level: WARNING
      handlers: [console]

    disable_existing_loggers: false
