apiVersion: v1
kind: Secret
metadata:
    name: synapse-signing-key
    namespace: matrix
type: Opaque
stringData:
    signing.key: ENC[AES256_GCM,data:NeiEMwJ1Vp5lE/4Kk5ptUs/pYlCgoTW6T1dnIcz+gK6xwsvz2e+3fKWrrgECueHQdTqhV4yE2FNTkQ==,iv:7/xdm0itD3Qqx0Xp8xMy3lwYXMkXUNM8QXMBMmbAqNM=,tag:+LAgjIkYsN+5hmCQ4V7qiQ==,type:str]
sops:
    age:
        - recipient: age1qt6zwvjzpvz8sed88tf3wj96t7694nnprnqdjls0w9vkxzzm6d8qag8snq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBka084Q2ZKYmVCSHdFbno2
            dDAvSVZ1ZkFjU05NYjEzWCtqc1BpUkc1UFFBCjZ5bzlGb2hnWFgwUDh6RmhnelQw
            dW5jclVEdVVrU2ZBSk90YjRkTDlmSVUKLS0tIFErZFkxb2lCSmdsN1NtcGpIZE55
            b2xuOTVuMmhjbFNOMnd3L09QYUtXb3MKdAJOo+34zV/uvJUYjeyTI2bHdDHmvRBj
            zdgQIGxWFAPnpICJK/PF4V97TnOhPxraFddofkVBRl0N+/51XjH0kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T20:18:13Z"
    mac: ENC[AES256_GCM,data:Gjui2Ax/SZYxk9uMwzZbscoEAhEfc0yR4ESVo/kiTm4bXWyWbxUYagrWcNLvKtCwLHyGM/ZHNK0H7LIrSUEGrfCX4OurJmuSRZ3hY4ZVBtZGF1IgtNTjMutlLrWS/j1oRhaT0kAaVriBvGgdlAg8jsdeudRbTeWRbfHKkFE+/qg=,iv:3gHoeBcfJ4/ikAUhvvGxgC6ztKSXF8yDmTTuD/6YXDY=,tag:EdIo0ieIHxOvVUiDjq+HGA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
