apiVersion: v1
kind: Secret
metadata:
    name: synapse-signing-key
    namespace: matrix
type: Opaque
stringData:
    signing.key: ENC[AES256_GCM,data:hRdwMDF7no+R7am1fns+w1GRCoYTRCgmfiBAzJinvPVxXAM6,iv:WLZVYLCxwqJSLMx55HUQQmADe2tWdICy0p56c5xaRqc=,tag:w4paqiE+pgCXfiZEsI2Rgg==,type:str]
sops:
    age:
        - recipient: age1qt6zwvjzpvz8sed88tf3wj96t7694nnprnqdjls0w9vkxzzm6d8qag8snq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBka084Q2ZKYmVCSHdFbno2
            dDAvSVZ1ZkFjU05NYjEzWCtqc1BpUkc1UFFBCjZ5bzlGb2hnWFgwUDh6RmhnelQw
            dW5jclVEdVVrU2ZBSk90YjRkTDlmSVUKLS0tIFErZFkxb2lCSmdsN1NtcGpIZE55
            b2xuOTVuMmhjbFNOMnd3L09QYUtXb3MKdAJOo+34zV/uvJUYjeyTI2bHdDHmvRBj
            zdgQIGxWFAPnpICJK/PF4V97TnOhPxraFddofkVBRl0N+/51XjH0kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T05:16:17Z"
    mac: ENC[AES256_GCM,data:rDfUSR56+FjgFcuEYcz9DF4BiLwR/jlkvzEKALncj0DhOUWITR0h/XVotrNZQfsAmPQei5tBsjuuM7W0S7LaUDi7cawaj8WEahfqiOX+KwaKxBSsLnRsREV15GWgXPTTb/fm9Er5A3vSMjNeW+id0jEkjUpR02kshNNQcOQJthU=,iv:pePXrQutxqhVvrpEn8x+ADBD88KBS5yudi99Xtso9mo=,tag:tpfl+6+6HE1yhIQkBIZiXQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
