---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets.yaml
  - vpn-secrets.yaml
  - nfs-media-pv.yaml
  - nfs-media-pvc.yaml
  - sonarr.yaml
  - radarr.yaml
  - lidarr.yaml
  - prowlarr.yaml
  - jellyseerr.yaml
  - bazarr.yaml
  - navidrome.yaml
  - byparr.yaml
  - recyclarr.yaml
  - recyclarr-configmap.yaml
  - qbittorrent.yaml
  - sabnzbd.yaml
  - unpackerr.yaml
  - middleware.yaml
  - ingress.yaml

configMapGenerator:
  - name: qbittorrent-init
    namespace: media
    files:
      - scripts/qbittorrent/01-patch-config.sh
      - scripts/qbittorrent/02-set-password.sh
      - scripts/qbittorrent/03-port-sync.sh
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/part-of: jellybuntu
  - name: sabnzbd-init
    namespace: media
    files:
      - scripts/sabnzbd/01-patch-config.sh
      - scripts/sabnzbd/02-configure-api.sh
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/part-of: jellybuntu
