---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets.yaml
  - nfs-media-pv.yaml
  - nfs-media-pvc.yaml
  - sonarr.yaml
  - radarr.yaml
  - lidarr.yaml
  - prowlarr.yaml
  - jellyseerr.yaml
  - bazarr.yaml
  - navidrome.yaml
  - byparr.yaml
  - recyclarr.yaml
  - recyclarr-configmap.yaml
  - ingress.yaml
