apiVersion: v1
kind: Secret
metadata:
    name: media-secrets
    namespace: media
type: Opaque
stringData:
    MEDIA_POSTGRES_PASSWORD: ENC[AES256_GCM,data:8KYYQKh84J8mYA==,iv:fxA+74qUzigjekDVK7SxvRo+ObSeSOwZi3P+8oc/Qfo=,tag:3ZtzqTOB9hERARtS9LMRHg==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:AIlC22ktD/JSrA==,iv:PBEsUvLFK8x5mXXIzyZ08Mv4ZfCkJHRhw4+/jVhP/rM=,tag:0UDlt/VIUEukPzGK/3OHbA==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:pbb8KGvnlRPFbw==,iv:N/YsK4FtMIVYKV7M6jtAfKjrmgE4hUx7daVPnjLc/g4=,tag:+lvTzGMhqxkwyGANYrnU7Q==,type:str]
    LIDARR_API_KEY: ENC[AES256_GCM,data:ctee35K59CyTWw==,iv:K+g82ICjg/ZVPLPkJoHkXRSBt2TDCrGMomd2BJ2FuIM=,tag:5svaK73QYTikHP73cO3uQg==,type:str]
    SABNZBD_API_KEY: ENC[AES256_GCM,data:GDUu2lR3V0osmQ==,iv:SqxFNQblO23i3ulzqxhJgtWv3OkNiP9Q93G6zt8XE2Y=,tag:hPo38vh2xRVdJLtjg6Q8Ag==,type:str]
sops:
    age:
        - recipient: age1qt6zwvjzpvz8sed88tf3wj96t7694nnprnqdjls0w9vkxzzm6d8qag8snq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydDFocElYWW5MelJJOVdX
            M2FYSnVKUSthT29CdmZRenJlTncreFoxbUhvCmx6ZFJWbFJzWVFkSkJUcDlyN3lF
            ZTNhckVBMVhJMU5RN1hDRk1JTVlkN2MKLS0tIFNVU0Y5Zmt4OUw1bmhhZzByRE1j
            d0JQeVduV1R5Uk1yQkl0NUc3dk10ZGMKnPdTduwBZKUme0RJaSCdqEpXUI4e4Zhz
            RKH9RD7FZ4od1tZo0WonSmBZ6oJuBRsOBUrWXnugzfLAhHFjzd5CvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T05:19:48Z"
    mac: ENC[AES256_GCM,data:DC/6N3FjEyMdPqP7V31iQwqVGLDo/lLZWeU6G7KtjtYvgmx9ABcHwFmHZhOg+lpuZJELOinavL94oTYVzs+gpCPaGMj4/AX6QxUPNDG7YTwidhxpug20mlYkDhu/hQpcIsUoIPVlRM4rLlWY7Cvfy8+JovUqumzOfjeD2cRFUpY=,iv:ZjJBoiRZCQ4KFHOiK1kezc8TUjaU3bphYWkzxAVGOhQ=,tag:PWQNZPWarw5CagPT1RVTzg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
