apiVersion: v1
kind: Secret
metadata:
    name: media-secrets
    namespace: media
type: Opaque
stringData:
    MEDIA_POSTGRES_PASSWORD: ENC[AES256_GCM,data:t5h4mZIopL16LtDhS7mQoBgwZomQUPtv/GCoClMMj+ZogdOZyWitE2pxmYytrKvV1FRdoOX8WyCct5v/4hQz8A==,iv:ofMtJ8fmk9AVaNR1Sb0h1dr5oHrSqfTSB5H4op9orXw=,tag:0MNiAyaDSUf4k9n55RK/Yw==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:PSdmPx4PaaHV4GW7j6yx8YbvHEBvu9yT7/inxcIrh0k=,iv:9MCYd//VtthPC8bnQwQOAbeUeLQh//zB/o4yQux0Rx4=,tag:Ln+IRog8Z3+kk/vWuEgs7w==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:0DkZhNOiUWsANhT7Jbyv26EgoLNYIx7uC2GquKCzuq8=,iv:Gzij8ABXlurrUMf9nK6t/P6rZYSbC8vWuXd5zKskRNw=,tag:M/kvs3Ot0K/D1JzxtLilvw==,type:str]
    LIDARR_API_KEY: ENC[AES256_GCM,data:uiKlKQBIEyVWiNjf7OJlvQ+/oaZcpvOj3i+Y6AyjQIk=,iv:tcDWxaXp8T8ubwLUp3JXmzrAT/jVJ8WXG3aDXSPvNqM=,tag:AXPMr32Xc4oZGB/CH0V/zw==,type:str]
    SABNZBD_API_KEY: ENC[AES256_GCM,data:SByhbPHSMlPctzfr4JSKxFeOvTPtcVBI4NIRV6NSd9o=,iv:BCmAPu+cstx9xLzNqAHYSKhFelhprbOD+Nr7zvcApJM=,tag:f3iHRdZwU1Hv7gqPH39mtQ==,type:str]
sops:
    age:
        - recipient: age1qt6zwvjzpvz8sed88tf3wj96t7694nnprnqdjls0w9vkxzzm6d8qag8snq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydDFocElYWW5MelJJOVdX
            M2FYSnVKUSthT29CdmZRenJlTncreFoxbUhvCmx6ZFJWbFJzWVFkSkJUcDlyN3lF
            ZTNhckVBMVhJMU5RN1hDRk1JTVlkN2MKLS0tIFNVU0Y5Zmt4OUw1bmhhZzByRE1j
            d0JQeVduV1R5Uk1yQkl0NUc3dk10ZGMKnPdTduwBZKUme0RJaSCdqEpXUI4e4Zhz
            RKH9RD7FZ4od1tZo0WonSmBZ6oJuBRsOBUrWXnugzfLAhHFjzd5CvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T20:19:20Z"
    mac: ENC[AES256_GCM,data:PUih3a8T6kjFDyU2yIy045k5Uv36i+md/HDVWDBDLHUQpORl8zIj1lMXYltN8WR1EYWrsOwUqCYCcqAm05JUBIRPD/IOvcYZ/jIppz4qfNUR01+VN//Z5CQuVI2JmQvgHk8DCcvpvdi3aBeUhtWQNuUqd5NTyDHn3iSisZhS+Bw=,iv:vs9px3vQBxR6WwZlg0RD7b389/uyYI1zuzpGnokgAvM=,tag:3XZ458+GCRX6yDBOLV0mVg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
