apiVersion: v1
kind: Secret
metadata:
    name: vpn-credentials
    namespace: media
type: Opaque
stringData:
    OPENVPN_USER: ENC[AES256_GCM,data:neRRGtlqBKcm275WN9mo0JlgZybjjxFejw==,iv:hGBE7+bBdPYAkvVmBagKULdV2nJlC69rdfzEidL/0zc=,tag:X1Ztlj67ayqDhFpyI7vwcw==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:fGljN7V1egqVCbf8L2to3o4DoSqbiBLYfA==,iv:LYX552vLeaXWO6DPqtfrx32ynxmiZuwj8VIGOYPTD+I=,tag:jIkze0zaI7A9fa5lEDX0WQ==,type:str]
sops:
    age:
        - recipient: age1qt6zwvjzpvz8sed88tf3wj96t7694nnprnqdjls0w9vkxzzm6d8qag8snq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadGVMMGsyM1Nkb0tiN2tU
            bC9OVy82OS91ZkpTN1NVa00vNHFDRzR5bkI4ClVUL0JTalpKUS9qUDcwN0FrNkx2
            cmNITUlTdDA3YmFZWHFhUEtyTjY4cFEKLS0tIE54UVFvMnJZRUtvNTlydWNNeEsz
            NnF1YzdrNVlGQWJyQ2JCdnVLUE9kWWsKgmdc5Wc3hPgFS0Vv0MadaMzfzv5KeXuV
            kmxG1zjHvZE/P1B/l/s4XCyUsY7dK+s7F5eGPcUnATj4qhVQ8ULEfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T16:02:15Z"
    mac: ENC[AES256_GCM,data:P1WWLu5/fdr+dShKHiUpuMwUOTRiXuM1HaZEgDh1DrWInLqXmUTQpJ1m4+0lRJErzWk93uITPNW7iTmxi0oQ3EkG1jKk3KqOw4h6raa+eu2Kfjj97MF17Wt6sVyk5qvySVNAN1vbmHBFiKwRr+/HAvUUBV9NhkuK1x7I8/8cRcE=,iv:R4Kx+xuL4OS+4Ix8kHAYpzCaSzXdLD6MiqLSg5wHWog=,tag:ZkGyxLav+73XNKo36jXmRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
