apiVersion: v1
kind: Secret
metadata:
    name: vpn-credentials
    namespace: media
type: Opaque
stringData:
    OPENVPN_USER: ENC[AES256_GCM,data:o8IPDVejL2s=,iv:4eWGQrp0jMcvrA2YCgFGOfqHVhLxjf6Q+wMarwQsxfQ=,tag:/+2iMzTDynthQvZNjsYJ6g==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:GmvRb5rD5Y8R+A==,iv:1fB3OUQGpzzXLkPIaqmSQePS7R7kF77ekHK8YtiWNC4=,tag:3gbRZ/WKC6iJsg9YdcoZuA==,type:str]
sops:
    age:
        - recipient: age1qt6zwvjzpvz8sed88tf3wj96t7694nnprnqdjls0w9vkxzzm6d8qag8snq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadGVMMGsyM1Nkb0tiN2tU
            bC9OVy82OS91ZkpTN1NVa00vNHFDRzR5bkI4ClVUL0JTalpKUS9qUDcwN0FrNkx2
            cmNITUlTdDA3YmFZWHFhUEtyTjY4cFEKLS0tIE54UVFvMnJZRUtvNTlydWNNeEsz
            NnF1YzdrNVlGQWJyQ2JCdnVLUE9kWWsKgmdc5Wc3hPgFS0Vv0MadaMzfzv5KeXuV
            kmxG1zjHvZE/P1B/l/s4XCyUsY7dK+s7F5eGPcUnATj4qhVQ8ULEfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T20:19:57Z"
    mac: ENC[AES256_GCM,data:a2qWiKswcpff3V8qYcs6SnLY0D1eY9X4NQI1h9WpiBwxjYT8FuMjzuGj3oOlWkk3cfMJ8dUjLNJ380BAaI1VSXHYGyuPeOYiPlS9qSlN/Xdz+PJxtcY312rQbkn1UShlBnoWEa0PIHTGv3N+a3dv9TsM9L847ahS00S9CPr+Yck=,iv:4iFBRfoqj+/Kwj4KulN6QGteuOUaNYqOg8/gTQkG6xw=,tag:diDi2gJ1nQH60uCXh+VTwA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
