---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: app-template
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: jellybuntu
spec:
  interval: 1m
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
  ref:
    semver: "4.6.x"
