---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: jellybuntu
spec:
  interval: 1m
  url: https://traefik.github.io/charts
