---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - nfs-media-pv.yaml
  - nfs-media-pvc.yaml
  - middleware.yaml
  - jellyfin.yaml
  - tdarr.yaml
  - ingress.yaml
