---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-gpu
  namespace: gpu
  labels:
    app.kubernetes.io/part-of: jellybuntu
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: nfs-media-gpu
  resources:
    requests:
      storage: 1Ti
