---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    app.kubernetes.io/part-of: jellybuntu
---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik-system
  labels:
    app.kubernetes.io/part-of: jellybuntu
---
apiVersion: v1
kind: Namespace
metadata:
  name: nfs-system
  labels:
    app.kubernetes.io/part-of: jellybuntu
