apiVersion: v1
kind: Secret
metadata:
    name: traefik-cloudflare
    namespace: traefik-system
type: Opaque
stringData:
    CF_DNS_API_TOKEN: ENC[AES256_GCM,data:1xFW3wGu7xFBgtO5tNia6hQyeT6vFsvvYAv4P5Q8nY/k2gRXRiuzZA==,iv:kPeG/nH9/AdszDHVs4n1DPNID2BjwVA2o/wPtxgodAw=,tag:kCWdXjiBcxsgVZxIsyJcGg==,type:str]
sops:
    age:
        - recipient: age1qt6zwvjzpvz8sed88tf3wj96t7694nnprnqdjls0w9vkxzzm6d8qag8snq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMEJTRFE0TGZFQ09kYW9G
            QkRaWnhaS2ZjQ3kyamYvZGNMdjZUSGMyMlM0CnRZVzBnb0xiUkNNelhMc1FaWnFr
            elJvelVXUERQRzZYR1BBY0xVR3NHdVUKLS0tIC9wa3UxQ1BQK2JQOCtQckFiSHJC
            VTJWNytMUE9wbTdaZjZNNU9CKzFMZXMKGeZBWgL/GkeiuCbOhmijhCZX6uCp7HmP
            hTENK26Wdwbe13M6poA2MN4jIbI3isRflYoFJCkgxJP//wzhD2ZgHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T21:25:50Z"
    mac: ENC[AES256_GCM,data:LJKG2VVz9NHa2EF/Q90dszMtBYf4rlZMcfJCP7q7tWb6E6GH0N7cbVzLpzWX4tLscKk+pzKCz22b1Qa8k5yudkyC3+54kb83QNEnlRSPNRhLd0BkZX5QFP9415mkIiggqeElEt1IY/2pkIbm25br7NuP2+0Po4/9tIYugngl54c=,iv:zpbJz4agq++WRVgcxyUtRPVqsDnvxxhhLsBn7N7CdMs=,tag:BTwud02H2IP//2rep9CfdQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
